### PR TITLE
Coverage reports negative test for Java

### PR DESCRIPTION
**Pull request by neomatrix369**
Added a negative test to simulate an error when retrieving coverage information fails, due to build config changed by participant

Fixes https://github.com/julianghionoiu/tdl-lord-of-runners/issues/15 (one of the many combinations per language)

```
+++ set -- -Dorg.gradle.appname=get_coverage_for_challenge.sh -classpath /srv/tdl-runner/gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain -p /srv/tdl-runner -q clean test jacocoTestReport --console=plain
+++ uname
++ '[' Linux = Darwin ']'
++ exec /usr/lib/jvm/java-8-openjdk-amd64/bin/java -Dorg.gradle.appname=get_coverage_for_challenge.sh -classpath /srv/tdl-runner/gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain -p /srv/tdl-runner -q clean test jacocoTestReport --console=plain

FAILURE: Build failed with an exception.

* What went wrong:
Task 'jacocoTestReport' not found in root project 'tdl-runner'.

* Try:
Run get_coverage_for_challenge.sh tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 3m 5s
Test failed due to non-zero exit code
   Actual exit code: 1       <=== see, see, see we can get exit codes but its a bit of a bash trick
   Expected exit code: 0
Test failed due to result mismatch
   Actual result: ''
   Expected result: '0'

~~~ Summary of test executions ~~~
  ~~~ Passed Tests ~~~
  0 test(s) passed

  ~~~ Failed Tests ~~~
  language=java|challenge=xyz|expected=0|actual=
  1 test(s) failed
```

_Do you see any other edge case worth capturing as a negative test?_ @julianghionoiu

### CODE REVIEW

**Comment by neomatrix369** [comment]
Happy to discuss if this can be further optimised but unless we add more tests to java and other languages it's not going to be easy or also efficient to find out. I suggest we be conservative with refactoring at this stage.

**Comment by neomatrix369** [comment]
My other test I'm thinking is Clover passes the build but our xml scanning portion of the script either fails or does not find the jacoco xml report.

So far I haven't had good the luck to fix the clover build!

**Comment by neomatrix369** [comment]
Existing tests are not affected:
```
~~~ Summary of test executions ~~~
  ~~~ Passed Tests ~~~
  language=java|challenge=SUM|expected=100|actual=100
  language=java|challenge=TST|expected=50|actual=50
  language=java|challenge=CHK|expected=0|actual=0
  language=java|challenge=xyz|expected=0|actual=0
  4 test(s) passed

  ~~~ Failed Tests ~~~
  0 test(s) failed

```

**Comment by julianghionoiu** [comment]
Hi Mani,
This approach does not feel right as it adds a lot of complexity and is very language specific.
I like the assertion on the exit code but not the way we force the failure.

After spending some time thinking about it, I think it is impossible to test all the negative scenarios and counter-productive.
My current preferred approach is to make it fail-fast by design. 
We need to ensure that all the get-coverage scripts have the "set -ex" flag set and we never do the " || true" hack.
This will ensure that all errors are propagated.

**Comment by neomatrix369** [comment]
Ok, we have decided to step back and revert our actions - I'll remove the commits that don't go well with this PR or create a new one.

Let's also create new PRs with the tdl-runner-xxx with changes propagating the errors to the top.

**Comment by neomatrix369** [comment]
PR #33 supercedes this PR

**Comment by neomatrix369** [comment]
I have to carefully remove the `|| true` as in most cases it can be removed but there might be exceptions. As you mentioned, build systems can return non-zero exit codes but also console runners / test runners / coverage tools can sometimes return non-zero exit codes for unknown or undocumented reasons even if in principle there isn't an issue with the final coverage output.

**Pull request closed without merging**
